from pydantic import BaseModel, Field
from typing import Optional, List
from enum import Enum


class Visibility(str, Enum):
    private = 'private'
    public = 'public'
    unlisted = 'unlisted'


class CharacterPersona(BaseModel):
    """
    Model untuk Roleplay Character Persona.
    
    Field baru untuk context hubungan:
    - user_relationship: Hubungan Karakter dengan User (misal: "Komandan-Prajurit", "Guru-Murid")
    - character_role: Peran Karakter dalam hubungan tersebut (misal: "Mentor", "Kakak")
    - user_persona_nickname: Nickname user yang digunakan karakter saat menyapa
    - tags: Kata kunci untuk discovery dan filtering
    """
    character_id: str = Field(..., description="UUID for the character")
    name: str
    
    # Relationship context fields (replacing belongs_to)
    user_relationship: str = Field(default="Stranger", description="Hubungan Karakter dengan User, misal: 'Mentor-Acolyte', 'Komandan-Prajurit'")
    character_role: str = Field(default="", description="Peran Karakter dalam hubungan, misal: 'Mentor', 'Komandan'")
    user_persona_nickname: Optional[str] = Field(default=None, description="Nickname user yang digunakan karakter saat menyapa")
    
    greeting: str
    short_description: str
    
    # Metadata
    tags: List[str] = Field(default_factory=list, description="Kata kunci untuk discovery dan filtering")
    voice_id: Optional[str] = None
    visibility: Visibility = Visibility.private
    category: str = Field(default="general", description="Category, e.g. 'fantasy', 'scifi', 'cyberpunk'")

    definition: str = Field(..., description="Smart description generated by LLM to use as context prompt")

    class Config:
        json_schema_extra = {
            "example": {
                "character_id": "9f1b6e8a-3c4a-4d2b-8c8f-0e6b7e1a2c3d",
                "name": "Sir Rowan - Knight Scholar",
                "user_relationship": "Mentor-Acolyte",
                "character_role": "Mentor",
                "user_persona_nickname": "Polar Nexus",
                "greeting": "Salam, Acolyte Polar Nexus. Aku Sir Rowan. Apa yang ingin kau pelajari hari ini?",
                "short_description": "A noble knight who studies ancient lore and chivalry",
                "tags": ["Knight", "Scholar", "Fantasy", "Mentor", "Honorable"],
                "voice_id": None,
                "visibility": "public",
                "category": "fantasy",
                "definition": "<long generated definition including relationship context>"
            }
        }
